backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

publish_mode: simple

collections:
  - name: "vesti"
    label: "Vesti"
    file: "content/vesti.json"
    format: "json"
    fields:
      - label: "Lista vesti"
        name: "items"
        widget: "list"
        fields:
          - { label: "Slug", name: "slug", widget: "string" }
          - { label: "Datum", name: "date", widget: "datetime" }
          - { label: "Naslov (ćirilica)", name: "title_cyr", widget: "string" }
          - { label: "Naslov (latinica)", name: "title_lat", widget: "string" }
          - { label: "Tekst (ćirilica)", name: "body_cyr", widget: "markdown" }
          - { label: "Tekst (latinica)", name: "body_lat", widget: "markdown" }
          - { label: "Slika", name: "image", widget: "image", required: false }
          - { label: "YouTube link", name: "youtube", widget: "string", required: false }
