backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "vesti"
    label: "Vesti"
    folder: "vesti"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Naslov", name: "title", widget: "string"}
      - {label: "Tekst", name: "body", widget: "markdown"}
      - {label: "Slika", name: "image", widget: "image", required: false}
      - {label: "YouTube", name: "youtube", widget: "string", required: false}
